### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by migdlp** [bitpay/wallet#12019]
I'm trying to install and start the wallet with:
```
npm install
npm run apply:bitpay
npm run start
```

but when I do `npm install` it fails. I've tried with node v10.12.6 and v12.22.11, but happends the same in both:

`$ npm install

> bitpay@12.11.6 postinstall C:\TFG-WalletPUF\wallet
> npm run env:dev && npm run prompt && npm run patch:all

> bitpay@12.11.6 env:dev C:\TFG-WalletPUF\wallet
> rm -f src/environments/index.ts && cp src/environments/dev.ts src/environments/index.ts

# Environment set to: dev

> bitpay@12.11.6 prompt C:\TFG-WalletPUF\wallet
>

#
#  Choose a distribution with:
#
#     $ npm run apply:copay
#              or
#     $ npm run apply:bitpay
#

"#" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitpay@12.11.6 prompt: `
npm ERR!
npm ERR!
npm ERR!
npm ERR!
npm ERR!
npm ERR! #
npm ERR! #  Choose a distribution with:
npm ERR! #
npm ERR! #     $ npm run apply:copay
npm ERR! #              or
npm ERR! #     $ npm run apply:bitpay
npm ERR! #
npm ERR! `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitpay@12.11.6 prompt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Miguel\AppData\Roaming\npm-cache\_logs\2022-03-29T17_03_11_668Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitpay@12.11.6 postinstall: `npm run env:dev && npm run prompt && npm run patch:all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitpay@12.11.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Miguel\AppData\Roaming\npm-cache\_logs\2022-03-29T17_03_11_714Z-debug.log
`

**Comment by migdlp** [comment]
When I run `npm run apply:bitpay` it seems to be all right. But with `npm run start` it returns many typescript errors and somo node errors:

```
$ npm run start

> bitpay@12.11.6 start C:\TFG-WalletPUF\wallet
> npm run ionic:serve


> bitpay@12.11.6 ionic:serve C:\TFG-WalletPUF\wallet
> ionic-app-scripts serve --nolivereload

[19:03:55]  ionic-app-scripts 3.2.3
[19:03:55]  watch started ...
[19:03:55]  build dev started ...
[19:03:55]  clean started ...
[19:03:55]  clean finished in 3 ms
[19:03:55]  copy started ...
[19:03:56]  deeplinks started ...
[19:03:57]  deeplinks finished in 1.16 s
[19:03:57]  transpile started ...
[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/bitcore-wallet-client/ts_build/lib/key.d.ts, line: 3
            Invalid character.

       L2:  export declare class Key {
       L3:      #private;
       L4:      id: any;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 3
            Initializers are not allowed in ambient contexts.

       L2:  declare class Connector implements IConnector {
       L3:      readonly protocol = "wc";
       L4:      readonly version = 1;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 4
            Initializers are not allowed in ambient contexts.

       L3:  readonly protocol = "wc";
       L4:  readonly version = 1;
       L5:  private _bridge;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 26
            An accessor cannot be declared in an ambient context.

      L25:  constructor(opts: IConnectorOpts);
      L26:  set bridge(value: string);
      L27:  get bridge(): string;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 27
            An accessor cannot be declared in an ambient context.

      L26:  set bridge(value: string);
      L27:  get bridge(): string;
      L28:  set key(value: string);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 28
            An accessor cannot be declared in an ambient context.

      L27:  get bridge(): string;
      L28:  set key(value: string);
      L29:  get key(): string;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 29
            An accessor cannot be declared in an ambient context.

      L28:  set key(value: string);
      L29:  get key(): string;
      L30:  set clientId(value: string);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 30
            An accessor cannot be declared in an ambient context.

      L29:  get key(): string;
      L30:  set clientId(value: string);
      L31:  get clientId(): string;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 31
            An accessor cannot be declared in an ambient context.

      L30:  set clientId(value: string);
      L31:  get clientId(): string;
      L32:  set peerId(value: string);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 32
            An accessor cannot be declared in an ambient context.

      L31:  get clientId(): string;
      L32:  set peerId(value: string);
      L33:  get peerId(): string;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 33
            An accessor cannot be declared in an ambient context.

      L32:  set peerId(value: string);
      L33:  get peerId(): string;
      L34:  set clientMeta(value: IClientMeta | null);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 34
            An accessor cannot be declared in an ambient context.

      L33:  get peerId(): string;
      L34:  set clientMeta(value: IClientMeta | null);
      L35:  get clientMeta(): IClientMeta | null;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 35
            An accessor cannot be declared in an ambient context.

      L34:  set clientMeta(value: IClientMeta | null);
      L35:  get clientMeta(): IClientMeta | null;
      L36:  set peerMeta(value: IClientMeta | null);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 36
            An accessor cannot be declared in an ambient context.

      L35:  get clientMeta(): IClientMeta | null;
      L36:  set peerMeta(value: IClientMeta | null);
      L37:  get peerMeta(): IClientMeta | null;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 37
            An accessor cannot be declared in an ambient context.

      L36:  set peerMeta(value: IClientMeta | null);
      L37:  get peerMeta(): IClientMeta | null;
      L38:  set handshakeTopic(value: string);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 38
            An accessor cannot be declared in an ambient context.

      L37:  get peerMeta(): IClientMeta | null;
      L38:  set handshakeTopic(value: string);
      L39:  get handshakeTopic(): string;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 39
            An accessor cannot be declared in an ambient context.

      L38:  set handshakeTopic(value: string);
      L39:  get handshakeTopic(): string;
      L40:  set handshakeId(value: number);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 40
            An accessor cannot be declared in an ambient context.

      L39:  get handshakeTopic(): string;
      L40:  set handshakeId(value: number);
      L41:  get handshakeId(): number;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 41
            An accessor cannot be declared in an ambient context.

      L40:  set handshakeId(value: number);
      L41:  get handshakeId(): number;
      L42:  get uri(): string;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 42
            An accessor cannot be declared in an ambient context.

      L41:  get handshakeId(): number;
      L42:  get uri(): string;
      L43:  set uri(value: string);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 43
            An accessor cannot be declared in an ambient context.

      L42:  get uri(): string;
      L43:  set uri(value: string);
      L44:  set chainId(value: number);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 44
            An accessor cannot be declared in an ambient context.

      L43:  set uri(value: string);
      L44:  set chainId(value: number);
      L45:  get chainId(): number;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 45
            An accessor cannot be declared in an ambient context.

      L44:  set chainId(value: number);
      L45:  get chainId(): number;
      L46:  set networkId(value: number);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 46
            An accessor cannot be declared in an ambient context.

      L45:  get chainId(): number;
      L46:  set networkId(value: number);
      L47:  get networkId(): number;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 47
            An accessor cannot be declared in an ambient context.

      L46:  set networkId(value: number);
      L47:  get networkId(): number;
      L48:  set accounts(value: string[]);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 48
            An accessor cannot be declared in an ambient context.

      L47:  get networkId(): number;
      L48:  set accounts(value: string[]);
      L49:  get accounts(): string[];

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 49
            An accessor cannot be declared in an ambient context.

      L48:  set accounts(value: string[]);
      L49:  get accounts(): string[];
      L50:  set rpcUrl(value: string);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 50
            An accessor cannot be declared in an ambient context.

      L49:  get accounts(): string[];
      L50:  set rpcUrl(value: string);
      L51:  get rpcUrl(): string;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 51
            An accessor cannot be declared in an ambient context.

      L50:  set rpcUrl(value: string);
      L51:  get rpcUrl(): string;
      L52:  set connected(value: boolean);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 52
            An accessor cannot be declared in an ambient context.

      L51:  get rpcUrl(): string;
      L52:  set connected(value: boolean);
      L53:  get connected(): boolean;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 53
            An accessor cannot be declared in an ambient context.

      L52:  set connected(value: boolean);
      L53:  get connected(): boolean;
      L54:  set pending(value: boolean);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 54
            An accessor cannot be declared in an ambient context.

      L53:  get connected(): boolean;
      L54:  set pending(value: boolean);
      L55:  get pending(): boolean;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 55
            An accessor cannot be declared in an ambient context.

      L54:  set pending(value: boolean);
      L55:  get pending(): boolean;
      L56:  get session(): {

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 56
            An accessor cannot be declared in an ambient context.

      L55:  get pending(): boolean;
      L56:  get session(): {
      L57:      connected: boolean;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/@walletconnect/core/dist/cjs/index.d.ts, line: 69
            An accessor cannot be declared in an ambient context.

      L68:  };
      L69:  set session(value: {
      L70:      connected: boolean;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/detect-browser/index.d.ts, line: 13
            Initializers are not allowed in ambient contexts.

      L12:      readonly type = "browser";
      L13:      constructor(name: Browser, version: string, os: OperatingSystem | null);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/detect-browser/index.d.ts, line: 18
            Initializers are not allowed in ambient contexts.

      L17:  readonly type = "node";
      L18:  readonly name: 'node';
      L19:  readonly os: NodeJS.Platform;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/detect-browser/index.d.ts, line: 28
            Initializers are not allowed in ambient contexts.

      L27:      readonly type = "bot-device";
      L28:      constructor(name: Browser, version: string, os: OperatingSystem | null, bot: string);

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/detect-browser/index.d.ts, line: 32
            Initializers are not allowed in ambient contexts.

      L31:  readonly type = "bot";
      L32:  readonly bot: true;
      L33:  readonly name: 'bot';

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/detect-browser/index.d.ts, line: 39
            Initializers are not allowed in ambient contexts.

      L38:  readonly type = "react-native";
      L39:  readonly name: 'react-native';
      L40:  readonly version: null;

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/eth-sig-util/dist/index.d.ts, line: 37
            Cannot find name 'unknown'.

      L36:      message: Record<string, unknown>;
      L38:  declare const TYPED_MESSAGE_SCHEMA: {

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/eth-sig-util/dist/index.d.ts, line: 84
            Cannot find name 'unknown'.

      L83:  encodeData(primaryType: string, data: Record<string, unknown>, types: Record<string, MessageTypeProperty[]>, useV4?: boolean): Buffer;
      L85:   * Encodes the type of an object by encoding a comma delimited list of its members

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/eth-sig-util/dist/index.d.ts, line: 110
            Cannot find name 'unknown'.

     L109:  hashStruct(primaryType: string, data: Record<string, unknown>, types: Record<string, unknown>, useV4?: boolean): Buffer;
     L111:   * Hashes the type of an object

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/eth-sig-util/dist/index.d.ts, line: 110
            Cannot find name 'unknown'.

     L109:  hashStruct(primaryType: string, data: Record<string, unknown>, types: Record<string, unknown>, useV4?: boolean): Buffer;
     L111:   * Hashes the type of an object

[19:04:18]  typescript: C:/TFG-WalletPUF/wallet/node_modules/eth-sig-util/dist/index.d.ts, line: 118
            Cannot find name 'unknown'.

     L117:  hashType(primaryType: string, types: Record<string, unknown>): Buffer;
     L119:   * Removes properties from a message object that are not defined per EIP-712

[19:04:18]  dev server running: http://localhost:8100/

[19:04:19]  copy finished in 23.48 s
(node:10116) UnhandledPromiseRejectionWarning: Error: A watch configured to watch the following paths failed to start. It likely that a file referenced does not exist: C:\TFG-WalletPUF\wallet\src\assets\**\*, C:\TFG-WalletPUF\wallet\src\index.html, C:\TFG-WalletPUF\wallet\src\manifest.json, C:\TFG-WalletPUF\wallet\src\service-worker.js, C:\TFG-WalletPUF\wallet\node_modules\ionicons\dist\fonts\**\*, C:\TFG-WalletPUF\wallet\node_modules\ionic-angular\fonts\**\*, C:\TFG-WalletPUF\wallet\node_modules\ionic-angular\polyfills\polyfills.js, C:\TFG-WalletPUF\wallet\node_modules\sw-toolbox\sw-toolbox.js
    at new BuildError (C:\TFG-WalletPUF\wallet\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at Timeout._onTimeout (C:\TFG-WalletPUF\wallet\node_modules\@ionic\app-scripts\dist\watch.js:71:20)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
(node:10116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10116) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
